import XCTest
import CryptoKit
@testable import NetworkKit

final class IncyLinkTests: XCTestCase {
    /// Cross-impl vector generated by the reference encoder with a fixed IV
    /// (00 01 … 0b). If our K1 or wire format drifts, this stops matching.
    private let vectorLink = "incy://crypt1/AAECAwQFBgcICQoLNyILfyzDv1FvhH4l0eWHS-TP-s1KN2bVUTyVcY-bEWgn--VSWUZVxckdd6q_TjLVTOOZ9HPEbKxEPf7qVSOCouKYwNmTHu8jrzplKgkxioOMuRgI"
    private let vectorURL = "https://example.com/sub?token=demo123"
    private let vectorName = "Demo VPN"

    func testKeyFingerprintMatchesReference() {
        XCTAssertEqual(IncyLink.derivedFingerprint, IncyLink.keyFingerprint)
    }

    func testDecodeReferenceVector() throws {
        let d = try IncyLink.decode(vectorLink)
        XCTAssertEqual(d.url, vectorURL)
        XCTAssertEqual(d.name, vectorName)
    }

    func testEncodeDeterministicMatchesReference() throws {
        // Same fixed nonce → must reproduce the reference link byte-for-byte.
        let nonce = try AES.GCM.Nonce(data: Data((0..<12).map { UInt8($0) }))
        let link = try IncyLink.encode(url: vectorURL, name: vectorName, nonce: nonce)
        XCTAssertEqual(link, vectorLink)
    }

    func testRoundTrip() throws {
        let link = try IncyLink.encode(url: "https://sub.example.org/abc", name: "Провайдер")
        XCTAssertTrue(link.hasPrefix(IncyLink.scheme))
        let d = try IncyLink.decode(link)
        XCTAssertEqual(d.url, "https://sub.example.org/abc")
        XCTAssertEqual(d.name, "Провайдер")
    }

    func testRoundTripWithoutName() throws {
        let link = try IncyLink.encode(url: "https://sub.example.org/xyz")
        let d = try IncyLink.decode(link)
        XCTAssertEqual(d.url, "https://sub.example.org/xyz")
        XCTAssertNil(d.name)
    }

    func testRejectsNonIncyLink() {
        XCTAssertThrowsError(try IncyLink.decode("https://example.com")) { error in
            XCTAssertEqual(error as? IncyLink.LinkError, .notAnIncyLink)
        }
    }

    func testRejectsTampered() {
        var chars = Array(vectorLink)
        chars[60] = chars[60] == "A" ? "B" : "A"
        XCTAssertThrowsError(try IncyLink.decode(String(chars)))
    }
}
